nixos-tests: fail on seccomp violations after each test run
We often experienced seccomp violations of CH in the wild and especially
since the latest bump to v52, it seems we missed a few of them in our
testing. Our testing never flagged them explicitely - this commit
changes that and let test cases fail similar to normal failures.

I verified that seccomp violations can only come from CH. We do not use
seccomp for any other software in our tests (or at least it works
properly).

Example output:

```text
  raise RuntimeError(f"Cloud Hypervisor caused seccomp violations\n{out}")
RuntimeError: Cloud Hypervisor caused seccomp violations
May 27 16:59:17 controllerVM kernel: audit: type=1326 audit(1779901157.729:2): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=1036 comm="net_0_qp0" exe="/nix/store/24l16kg6lk633lq9464igkzr9lirkx0q-cloud-hypervisor-52.0.0/bin/cloud-hypervisor" sig=0 arch=c000003e syscall=89 compat=0 ip=0x7f825ab5cb4b code=0x7ffc0000
```

On-behalf-of: SAP philipp.schuster@sap.com
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>