nix: Obtain Ubuntu Jammy from stable URL
It seems the Jammy image used by us was removed form the current URL.
Trying to download it fails with the following error:

```
jammy-server-cloudimg-amd64.img> error: cannot download jammy-server-cloudimg-amd64.img from any mirror
error: Cannot build '/nix/store/dc7mwsshycq6jsggkjqi7zc8qlnzn5cc-jammy-server-cloudimg-amd64.img.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/9sk1780wnccvxp8vzg85fd9fwa4h8wj7-jammy-server-cloudimg-amd64.img
       Last 17 log lines:
       > structuredAttrs is enabled
       >
       > trying https://cloud-images.ubuntu.com/jammy/20260320/jammy-server-cloudimg-amd64.img
       >   % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
       >                                  Dload  Upload  Total   Spent   Left   Speed
       >   0      0   0      0   0      0      0      0                              0
       > curl: (22) The requested URL returned error: 404
       > Warning: Problem (retrying all errors). Retrying in 1 second. 3 retries left.
       >   0      0   0      0   0      0      0      0                              0
       > curl: (22) The requested URL returned error: 404
       > Warning: Problem (retrying all errors). Retrying in 2 seconds. 2 retries left.
       >   0      0   0      0   0      0      0      0                              0
       > curl: (22) The requested URL returned error: 404
       > Warning: Problem (retrying all errors). Retrying in 4 seconds. 1 retry left.
       >   0      0   0      0   0      0      0      0                              0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download jammy-server-cloudimg-amd64.img from any mirror
       For full logs, run:
         nix log /nix/store/dc7mwsshycq6jsggkjqi7zc8qlnzn5cc-jammy-server-cloudimg-amd64.img.drv
```

We fix this issue by using the stable release URL to download the image.
The hash was generated via
`nix hash convert --hash-algo sha256 --to sri` from the checksum
released by Ubuntu and checked against the current one.[0] We can
therefore be sure this is the same image as before.

[0] http://cloud-images-archive.ubuntu.com/releases/jammy/release-20260320/SHA256SUMS

On-behalf-of: SAP pascal.scholz@sap.com
Signed-off-by: Pascal Scholz <pascal.scholz@cyberus-technology.de>